### PR TITLE
No classList for no-touch browsers.

### PR DESCRIPTION
**Pull request by Zegnat**
To keep touch browsers from worrying about `:active` and `:hover` you suggest using the `.no-touch` class in CSS. However, because you are using `classList`, this class will not be available to over 15% of the web’s visitors (IE 8 and 9 per September 2013, [StatCounter](http://gs.statcounter.com/#browser_version-ww-monthly-201309-201309-bar)).

This patch modifies the no-touch part of the code to use simple string operations on `className` instead. I am assuming touch browsers support classList, and according to [Can I use…](http://caniuse.com/#search=classList) they do, so that part of the code has been left untouched.

### CODE REVIEW

**Comment by jonathanstark** [comment]
Here's an example of what I mean:

https://gist.github.com/jonathanstark/6902015

**Comment by Zegnat** [comment]
> Obviously, devs will have to mod the CSS, but there’s no way around that.

There might be. Iterate over all [`cssRules`](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet) and replace those that contain `a:(hover|active)` with the exact same except with the added `activeClass`. I am not sure what the best RegEx is, else I would’ve made a pull.

Might be worth some thought.

**Comment by jonathanstark** [comment]
Very interesting idea. In my experience, though, the CSS changes that need to be made are more complex than a find/replace type of activity. Hm...

**Comment by Zegnat** [comment]
> _[…]_ the CSS changes that need to be made are more complex than a find/replace type of activity.

Maybe. The following is completely hypothetical and pieced together from looking at PPK’s [DOM CSS Level 2 table](http://www.quirksmode.org/dom/w3c_css.html) and MDN, but sounds like something that should be possible:
1. Iterate over every [`CSSRule`](https://developer.mozilla.org/en-US/docs/Web/API/CSSRule),
2. take the [`selectorText`](http://www.quirksmode.org/dom/w3c_css.html#t33),
   1. `split` it on commas,
   2. look for `:hover`/`:active` per part,
   3. add the `.no-touch` if a pointer action was found,
   4. `join` them again,
3. take the [`style.cssText`](http://www.quirksmode.org/dom/w3c_css.html#t30) (not plain `cssText`),
4. use the modified `selectorText` and unmodified `style.cssText` to [`insertRule`](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet.insertRule),
5. run [`deleteRule`](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/deleteRule) on the old one.

The big problems are with 2.1 and 2.2. I don’t know what sort of RegEx would be needed to do this correctly. Commas are allowed inside attribute selectors (e.g. `a[data-comma=","]`) so you cannot do a straight `split`.

Or maybe there are other problems. PPK’s table hasn’t been updated yet so I have no clue about mobile browser support. Still, it’s an interesting brain teaser.

**Pull request merged**
